"""Generated report footers must name the operator by callsign only (CONTROL-01).

Scope: only the strings returned by footer_block() and format_audit_footer().
This test deliberately does not scan repository docs.

Rather than listing names to block (which would itself publish them), every
word in a footer must come from a fixed allowlist, so no personal name, model
attribution, or sign-off can slip in without updating this file.
"""

import re

import pytest

from nexus.analyze import footer_block
from nexus.audit import format_audit_footer

CALLSIGN = "CONTROL-01"

# Every word that may appear in a generated footer (case-sensitive).
ALLOWED_WORDS = {
    # callsign line
    CALLSIGN, "generated", "automatically",
    # audit header line
    "Self-audit", "by", "the", "Nexus", "closed-loop", "optimisation", "system",
    # alignment line
    "Aligned", "with", "xAI", "truth-seeking", "X", "high-signal", "SpaceX",
    "first-principles", "building",
    # trailing pointer lines
    "World-first", "progressive", "monetisation", "active", "see", "See",
    "MONETIZATION_PROTOCOL.md", "CHECKS_AND_BALANCES.md", "and",
    "AUTOMATED_DEVELOPMENT.md",
}

FOOTERS = {
    "analysis": footer_block,
    "audit": format_audit_footer,
}


def _words(text: str) -> list[str]:
    return re.findall(r"[A-Za-z0-9][A-Za-z0-9_.\-]*[A-Za-z0-9]|[A-Za-z0-9]", text)


@pytest.mark.parametrize("name", sorted(FOOTERS))
def test_footer_contains_callsign(name):
    assert CALLSIGN in FOOTERS[name]()


@pytest.mark.parametrize("name", sorted(FOOTERS))
def test_footer_has_no_attribution_or_sign_off(name):
    text = FOOTERS[name]()
    lowered = text.lower()
    assert "powered by" not in lowered
    assert "ara &" not in lowered
    assert "love" not in lowered
    assert "💕" not in text
    assert "❤" not in text
    # No model/provider attribution in the footer.
    assert "grok" not in lowered
    assert "claude" not in lowered


@pytest.mark.parametrize("name", sorted(FOOTERS))
def test_footer_words_are_allowlisted(name):
    unexpected = [w for w in _words(FOOTERS[name]()) if w not in ALLOWED_WORDS]
    assert not unexpected, f"{name} footer has non-allowlisted words: {unexpected}"


@pytest.mark.parametrize("name", sorted(FOOTERS))
def test_footer_says_generated_by_at_most_once(name):
    assert FOOTERS[name]().lower().count("generated by") <= 1
